[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]

[project]
name = "AccelExplorer"
description = "Tool for exploring acceleration data"
dynamic = ["version"]

[tool.setuptools_scm]
write_to = "app/_version.py"